spring:
  application:
    name: kafka-server

server:
  port: 18104

eureka:
  enable-self-preservation: false # 设置为false表示关闭保护模式
  eviction-interval-timer-in-ms: 60000 # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:18000/eureka
  instance:
    instance-id: kafka  # 在信息列表时显示主机名称
    prefer-ip-address: true