spring:
  application:
    name: quarzt-server
    datasource:
    url: jdbc:mysql://118.190.97.96:3306/quartz
    username: 
    password: 
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
logging:
  level:
    cn.study.service: DEBUG
server:
  port: 8102
eureka:
  enable-self-preservation: false # 设置为false表示关闭保护模式
  eviction-interval-timer-in-ms: 60000 # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: quarzt  # 在信息列表时显示主机名称
    prefer-ip-address: true